### ISSUE TITLE
can not use rdma_client, when using hca mode with calico

### ISSUE THREAD

**Issue by asdfsx** [Mellanox/k8s-rdma-sriov-dev-plugin#18]
To use hca mode with calico, I add these settings
```
            - name: IP_AUTODETECTION_METHOD
              value: "interface=enp175s0"
            - name: IP6_AUTODETECTION_METHOD
              value: "interface=enp175s0"
```

After create the whole network, I try to do connectivity test using rdma_server/rdma_client.
so I create to 2 pod first
```
apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
spec:  # specification of the pod's contents
  containers:
  - name: iperf-server
    image: "asdfsx/mofed_benchmark"
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        rdma/hca: 1
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    stdin: true
    tty: true
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-1
spec:  # specification of the pod's contents
  containers:
  - name: iperf-client-1
    image: "asdfsx/mofed_benchmark"
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        rdma/hca: 1
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    stdin: true
    tty: true
```
The image `asdfsx/mofed_benchmark` is builded by using this [dockerfile](https://github.com/Mellanox/mofed_dockerfiles/blob/master/Dockerfile.centos7.2.mofed-4.4)

Then start the rdma_server
```
$ kubectl exec -it iperf-server -- rdma_server
rdma_server: start
```

Start the rdma_client, but got error
```
$ kubectl exec -it iperf-client-1 -- rdma_client -s 10.244.0.8
rdma_client: start
rdma_create_ep: No such device
rdma_client: end -1
command terminated with exit code 255
```
I want to know why this happen.I'm totally confused~~~
